# Generated by Django 4.0.4 on 2022-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='default',
            field=models.CharField(choices=[('Main Product Image', 'Main Product Image'), ('Sub Img 1', 'Sub Img 1'), ('Sub Img 2', 'Sub Img 2')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_name',
            field=models.ImageField(upload_to='product'),
        ),
    ]
