# Generated by Django 4.0.4 on 2022-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='default',
            field=models.CharField(choices=[('Main Product Image', 'Main Product Image'), ('Sub Img 1', 'Sub Img 1'), ('Sub Img 2', 'Sub Img 2')], max_length=20),
        ),
    ]
